# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teable_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from pdf_generator import generate_pdf
from datetime import datetime
from PyQt5.QtWidgets import QTableWidgetItem
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QLabel, QPushButton, QTableWidget, QTableWidgetItem


class Ui_Dialog(object):

    def setupUi(self, Dialog):

        Dialog.setObjectName("Dialog")
        Dialog.resize(1085, 855)


        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 50, 261, 41))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 47, 13))
        self.label.setObjectName("label")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(300, 50, 91, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(310, 30, 111, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(620, 50, 69, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(600, 30, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(710, 30, 111, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(730, 50, 69, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(830, 50, 191, 41))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(840, 30, 47, 13))
        self.label_5.setObjectName("label_5")
        self.textEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 120, 1031, 71))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 100, 91, 16))
        self.label_6.setObjectName("label_6")
        self.textEdit_5 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 220, 511, 91))
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 200, 91, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(540, 200, 91, 16))
        self.label_8.setObjectName("label_8")
        self.textEdit_6 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_6.setGeometry(QtCore.QRect(540, 220, 501, 91))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_7.setGeometry(QtCore.QRect(10, 340, 511, 41))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 320, 47, 13))
        self.label_9.setObjectName("label_9")
        self.textEdit_8 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_8.setGeometry(QtCore.QRect(10, 420, 511, 61))
        self.textEdit_8.setObjectName("textEdit_8")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 400, 91, 16))
        self.label_10.setObjectName("label_10")
        self.textEdit_9 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_9.setGeometry(QtCore.QRect(10, 520, 511, 61))
        self.textEdit_9.setObjectName("textEdit_9")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(20, 500, 91, 16))
        self.label_11.setObjectName("label_11")
        self.textEdit_10 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_10.setGeometry(QtCore.QRect(10, 610, 511, 61))
        self.textEdit_10.setObjectName("textEdit_10")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(20, 590, 91, 16))
        self.label_12.setObjectName("label_12")
        self.textEdit_11 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_11.setGeometry(QtCore.QRect(10, 700, 521, 151))
        self.textEdit_11.setObjectName("textEdit_11")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(10, 680, 161, 16))
        self.label_13.setObjectName("label_13")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(570, 340, 501, 351))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(960, 810, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 810, 101, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(400, 50, 111, 16))
        self.label_14.setObjectName("label_14")
        self.textEdit_12 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_12.setGeometry(QtCore.QRect(430, 50, 91, 21))
        self.textEdit_12.setObjectName("textEdit_12")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(530, 50, 51, 16))
        self.label_15.setObjectName("label_15")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        Dialog.setStyleSheet("background-color: rgb(216, 212, 204);")
        # Apply white background to all QTextEdit widgets
        for text_edit in [
            self.textEdit, self.textEdit_2, self.textEdit_3, self.textEdit_4,
            self.textEdit_5, self.textEdit_6, self.textEdit_7, self.textEdit_8,
            self.textEdit_9, self.textEdit_10, self.textEdit_11, self.textEdit_12, self.comboBox,self.comboBox_2,
        ]:
            text_edit.setStyleSheet("background-color: white;")

        header = self.tableWidget.horizontalHeader()
        header.setStyleSheet("QHeaderView::section { background-color: rgb(216, 212, 204); color: black; }")

        header_vertical = self.tableWidget.verticalHeader()
        header_vertical.setStyleSheet("QHeaderView::section { background-color: rgb(216, 212, 204); color: black; }")

        self.tableWidget.setColumnWidth(0, 150)
        self.tableWidget.setColumnWidth(1, 150)

        # Loop through each row and column to change the background color of every cell
        for row in range(self.tableWidget.rowCount()):
            for col in range(self.tableWidget.columnCount()):
                item = self.tableWidget.item(row, col)
                if item is None:
                    item = QTableWidgetItem()
                    self.tableWidget.setItem(row, col, item)
                item.setBackground(QColor(255, 255, 255))  # Set background to white

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Prescription Manager"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("Dialog", "Name:"))
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Age:"))
        self.comboBox.setItemText(0, _translate("Dialog", "Male"))
        self.comboBox.setItemText(1, _translate("Dialog", "Female"))
        self.comboBox.setItemText(2, _translate("Dialog", "Other"))
        self.label_3.setText(_translate("Dialog", "Sex"))
        self.label_4.setText(_translate("Dialog", "Bed"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "7"))
        self.textEdit_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "UHID"))
        self.textEdit_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "Diagnosis:"))
        self.textEdit_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "Consultants:"))
        self.label_8.setText(_translate("Dialog", "Junior Residents:"))
        self.textEdit_6.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_7.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "Feeds:"))
        self.textEdit_8.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "Ionotropes:"))
        self.textEdit_9.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_11.setText(_translate("Dialog", "Antimicrobials"))
        self.textEdit_10.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "Miscellaneous:"))
        self.textEdit_11.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_13.setText(_translate("Dialog", "Nursing and Supportive Care"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "Date"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "Weight"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "TFR"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "TFV"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "IVF"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "IVM"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "Glucose"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "GIR"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "Feeds"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "K"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "Na"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Values"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Units"))

        self.pushButton.setText(_translate("Dialog", "Scan"))
        self.pushButton_2.setText(_translate("Dialog", "Print"))
        self.label_14.setText(_translate("Dialog", "Years"))
        self.textEdit_12.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_15.setText(_translate("Dialog", "Months"))



        self.pushButton_2.clicked.connect(self.save_fields_and_generate_pdf)
        self.pushButton.clicked.connect(self.open_second_window)



        item = QtWidgets.QTableWidgetItem("DD/MM/YY")
        item.setFlags(item.flags() & ~QtCore.Qt.ItemIsEditable)  # Make the item non-editable
        self.tableWidget.setItem(0, 1, item)

        item = QtWidgets.QTableWidgetItem(f"{datetime.now().strftime('%d/%m/%Y')}")

        self.tableWidget.setItem(0, 0, item)

    def save_fields_and_generate_pdf(self):

        row_count = self.tableWidget.rowCount()
        # Iterate through all rows to get the row names
        row_names = []
        for row in range(row_count):
            row_name = self.tableWidget.verticalHeaderItem(row).text()
            row_names.append(row_name)

        # Assuming your table widget is named `tableWidget`

        column_count = self.tableWidget.columnCount()
        column_names = []
        for column in range(column_count):
            column_name = self.tableWidget.horizontalHeaderItem(column).text()
            column_names.append(column_name)

        print("Column Names:", column_names)


        """
        Collects all text from the widgets into a dictionary and returns it.
        """
        fields_data = {
            "Name": self.textEdit.toPlainText(),
            "Age": f'{self.textEdit_2.toPlainText()} years  {self.textEdit_12.toPlainText()} months',
            "Sex": self.comboBox.currentText(),
            "Bed": self.comboBox_2.currentText(),
            "UHID": self.textEdit_3.toPlainText(),
            "Diagnosis": self.textEdit_4.toPlainText(),
            "Consultants": self.textEdit_5.toPlainText(),
            "Junior Residents": self.textEdit_6.toPlainText(),
            "Feeds": self.textEdit_7.toPlainText(),
            "Ionotropes": self.textEdit_8.toPlainText(),
            "Antimicrobials": self.textEdit_9.toPlainText(),
            "Miscellaneous": self.textEdit_10.toPlainText(),
            "Nursing and Supportive Care": self.textEdit_11.toPlainText(),
            # "Table": self.tableWidget.toPlainText(),

        }
        #print(type(fields_data), fields_data)  # Debug output, replace with necessary processing\

        # Extract text from each cell
        for row in range(ui.tableWidget.rowCount()):
            for col in range(ui.tableWidget.columnCount()):
                item = ui.tableWidget.item(row, col)
                if item:  # Check if the cell is not empty
                    print(f"Cell ({row_names[row]}, {column_names[col]}): {item.text()}")
                    fields_data[f"{row_names[row]}_{column_names[col]}"] = str(item.text())
                    pass

                else:
                    print(f"Cell ({row_names[row]}, {column_names[col]}): 0x0")
                    fields_data[f"{row_names[row]}_{column_names[col]}"] = "N/A"
                    pass

        print(type(fields_data), fields_data)

        generate_pdf(fields_data)

    def open_second_window(self):
        self.second_window = SecondWindow()
        self.second_window.show()

class SecondWindow(QWidget):
    def __init__(self):
        super().__init__()

        # Set the window title and geometry
        self.setWindowTitle('Second Window')
        self.setGeometry(150, 150, 400, 300)  # Window position and size (x, y, width, height)

        # Create a layout
        layout = QVBoxLayout(self)

        # Add a label
        label = QLabel("Welcome to the second window!", self)
        layout.addWidget(label)

        # Add a table
        self.tableWidget = QTableWidget(self)
        self.tableWidget.setRowCount(3)  # Set the number of rows
        self.tableWidget.setColumnCount(3)  # Set the number of columns

        # Set the headers for both rows and columns
        headers = ["med1", "med2", "med3"]
        self.tableWidget.setHorizontalHeaderLabels(headers)  # Set column headers
        self.tableWidget.setVerticalHeaderLabels(headers)  # Set row headers

        # Optional: Fill the table with some data
        for row in range(3):
            for col in range(3):
                item = QTableWidgetItem(f"Data {row + 1}-{col + 1}")
                self.tableWidget.setItem(row, col, item)

        # Set size policy to make the table stretch with the window
        self.tableWidget.setSizePolicy(
            1,  # Horizontal Stretch (Expanding)
            1  # Vertical Stretch (Expanding)
        )

        # Add table to layout
        layout.addWidget(self.tableWidget, 1)  # The '1' is the stretch factor

        # Add a button to close the window
        button = QPushButton("Close", self)
        button.clicked.connect(self.close)  # Connect the button to the close method
        layout.addWidget(button)

        # Set the layout for the window
        self.setLayout(layout)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    QtWidgets.QApplication.setStyle(QtWidgets.QStyleFactory.create('Windows'))

    Dialog.show()
    sys.exit(app.exec_())
